### ISSUE TITLE
package.json in browser-code

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/AutolabJS#200]
The dependencies such as FileSaver.js, jquery.js and material.js have been copied into [main_server/public/js directory](https://github.com/AutolabJS/AutolabJS/tree/master/main_server/public/js) . It is better to use npm's package.json here.

Some helpful hints on a way to use package.json for browser-side code: example [specification](https://github.com/prasadtalasila/BITS-Darshini/blob/dev/src/main/webapp/WEB-INF/package.json) and [invocation](https://github.com/prasadtalasila/BITS-Darshini/blob/dev/scripts/install.sh#L39). 

We need to create package.json in [main_server/public/js directory](https://github.com/AutolabJS/AutolabJS/tree/master/main_server/public/js) and use the command, 
```shell
> npm install --prefix main_server/public/js
```
to download the specified third-party packages.

**Comment by AnkshitJain** [comment]
The packages for [jquery](https://www.npmjs.com/package/jquery),[materialize-css](https://www.npmjs.com/package/materialize-css) and [filesaver](https://www.npmjs.com/package/file-saver) are available on npm. The package.json will install all these inside main_server/public/js/node_modules folder and appropriate changes will be made to the files that access them. The css files for Materialize.css are available inside the same directory and this can directly be used from the npm package instead of keeping a file inside the main_server/public/css.

**Comment by prasadtalasila** [comment]
sounds good. The data of website-load.bats tests would undergo changes as well.

**Comment by AnkshitJain** [comment]
Yeah, I'll make the relevant changes to the tests as well.

**Comment by prasadtalasila** [comment]
completed in PR #212
