### ISSUE TITLE
bats tests for newly introduced I/O test structure.

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/AutolabJS#201]
The newly introduced I/O test structure allows variable number of I/O tests across labs. We need two to three bats tests to verify this newly introduced feature.

All the tests for this feature can go into [io-tests.bats](https://github.com/AutolabJS/AutolabJS/blob/dev/tests/functional_tests/io-tests.bats)

**Comment by AnkshitJain** [comment]
The [test.sh](https://github.com/AutolabJS/AutolabJS/blob/dev/docs/examples/io_tests/test_cases/cpp14/setup/Test.sh) file was changed and could run any number of tests, rather than having one test.sh for one test case. I will add up the tests for this, although this has been verified multiple times during the labs.

**Comment by prasadtalasila** [comment]
Not a priority right now.
